### ISSUE TITLE
pip install incompatible dependencies

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#41] opened 2018-07-01 20:58 UTC
```
salvadord-MBP% pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple netpyne_ui
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Requirement already satisfied: netpyne_ui in ./Documents/ISB/Models/NetPyNe-UI (0.1)
Requirement already satisfied: jupyter_geppetto==0.3.9 in ./Documents/ISB/Models/NetPyNe-UI/org.geppetto.frontend.jupyter/src (from netpyne_ui) (0.3.9)
Requirement already satisfied: netpyne in ./Documents/ISB/Models/netpyne_repo (from netpyne_ui) (0.7.8)
Requirement already satisfied: ipython<6.0.0,>=4.0.0 in ./anaconda/lib/python2.7/site-packages (from jupyter_geppetto==0.3.9->netpyne_ui) (5.3.0)
Requirement already satisfied: jupyter_client<5.0.0,>=4.0.0 in ./anaconda/lib/python2.7/site-packages (from jupyter_geppetto==0.3.9->netpyne_ui) (4.4.0)
Requirement already satisfied: notebook<5.0.0,>=4.0.0 in ./anaconda/lib/python2.7/site-packages (from jupyter_geppetto==0.3.9->netpyne_ui) (4.4.1)
Requirement already satisfied: nbconvert<5.0.0,>=4.0.0 in ./anaconda/lib/python2.7/site-packages (from jupyter_geppetto==0.3.9->netpyne_ui) (4.3.0)
Requirement already satisfied: ipywidgets<6.0,>=5.1.5 in ./anaconda/lib/python2.7/site-packages (from jupyter_geppetto==0.3.9->netpyne_ui) (5.2.3)
Requirement already satisfied: numpy in ./anaconda/lib/python2.7/site-packages (from netpyne->netpyne_ui) (1.14.2)
Requirement already satisfied: scipy in ./anaconda/lib/python2.7/site-packages (from netpyne->netpyne_ui) (0.19.1)
Requirement already satisfied: matplotlib in ./anaconda/lib/python2.7/site-packages (from netpyne->netpyne_ui) (2.2.2)
Requirement already satisfied: jupyter-core in ./anaconda/lib/python2.7/site-packages (from jupyter_client<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (4.3.0)
Requirement already satisfied: pyzmq>=13 in ./anaconda/lib/python2.7/site-packages (from jupyter_client<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (16.0.2)
Requirement already satisfied: traitlets in ./anaconda/lib/python2.7/site-packages (from jupyter_client<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (4.3.2)
Requirement already satisfied: tornado>=4 in ./anaconda/lib/python2.7/site-packages (from notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (4.5.1)
Requirement already satisfied: jinja2 in ./anaconda/lib/python2.7/site-packages (from notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (2.9.6)
Requirement already satisfied: ipython-genutils in ./anaconda/lib/python2.7/site-packages (from notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (0.2.0)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in ./anaconda/lib/python2.7/site-packages (from notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (0.6)
Requirement already satisfied: ipykernel in ./anaconda/lib/python2.7/site-packages (from notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (4.6.1)
Requirement already satisfied: nbformat in ./anaconda/lib/python2.7/site-packages (from notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (4.3.0)
Requirement already satisfied: mistune!=0.6 in ./anaconda/lib/python2.7/site-packages (from nbconvert<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (0.7.4)
Requirement already satisfied: entrypoints in ./anaconda/lib/python2.7/site-packages (from nbconvert<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (0.2.2)
Requirement already satisfied: pygments in ./anaconda/lib/python2.7/site-packages (from nbconvert<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (2.2.0)
Requirement already satisfied: widgetsnbextension==1.*,>=1.2.6 in ./anaconda/lib/python2.7/site-packages (from ipywidgets<6.0,>=5.1.5->jupyter_geppetto==0.3.9->netpyne_ui) (1.2.6)
Requirement already satisfied: backports.functools-lru-cache in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (1.5)
Requirement already satisfied: cycler>=0.10 in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (2.7.2)
Requirement already satisfied: six>=1.10 in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (1.11.0)
Requirement already satisfied: pytz in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (2018.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (1.0.1)
Requirement already satisfied: subprocess32 in ./anaconda/lib/python2.7/site-packages (from matplotlib->netpyne->netpyne_ui) (3.2.7)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda/lib/python2.7/site-packages (from jinja2->notebook<5.0.0,>=4.0.0->jupyter_geppetto==0.3.9->netpyne_ui) (0.23)
Requirement already satisfied: setuptools in ./anaconda/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib->netpyne->netpyne_ui) (39.0.1)
allensdk 0.14.3 has requirement matplotlib<2.0.0,>=1.4.3, but you'll have matplotlib 2.2.2 which is incompatible.
allensdk 0.14.3 has requirement pandas<0.20.0,>=0.16.2, but you'll have pandas 0.21.0 which is incompatible.
bqplot 0.9.0 has requirement ipywidgets>=6.0.0, but you'll have ipywidgets 5.2.3 which is incompatible.
```

**Comment by adrianq** [comment] 2018-07-02 08:33
The problem is that you have another jupyter extension [bqplot](https://github.com/bloomberg/bqplot). This jupyter extension requires a different ipywidgets version (this will be solved once we update to python 3). This jupyter extension is not needed by NetPyNE-UI and it was probably installed during an installation test if I am not wrong. You can either uninstall bqplot (pip uninstall bqplot) or install NetPyNE-UI in a virtual environment. There is not too much we can do here as this is a classic python problem and the reason why many people use virtual environment

**Comment by salvadord** [comment] 2018-07-02 22:44
sounds good, thx! -- so maybe we should add some version of this (including steps to create virtual env?) to the install instructions / 'troubleshooting' guide

**Comment by salvadord** [comment] 2018-07-03 21:49
Updating the repos in the dev version worked ok

![image](https://user-images.githubusercontent.com/8440562/42246121-6c7898a8-7ee9-11e8-9ce1-2299f56fa6d2.png)

**Comment by tarelli** [comment] 2018-07-04 14:41
This is due to mixing development installation of netpyne with production one, won't fix.

**Closed by tarelli** 2018-07-04 14:41 UTC
