### ISSUE TITLE
Notes from a fresh install...

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#211] opened 2021-02-23 12:07 UTC
I've just reinstalled NetPyNE-UI and used a new conda env. Some things I noticed:

1) After building (python utilities/install.py) I get a new x86_64 in the root dir. If I leave this there and start NP (./NetPyNE-UI) I get the dreaded `[I 11:32:34.920 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports` error after  it loads the mods, and the app stalls at the splash screen. If I remove x86_64, it starts fine. 

2) The contents of app.log are still pretty minimal:
```
2021-02-23 11:19:44,876 - matplotlib.pyplot - DEBUG
2021-02-23 11:19:54,188 - root - INFO
2021-02-23 11:19:54,191 - root - DEBUG
```
@lrebscher suggested this was a known issue which was fixed somewhere

3) The branch of netpyne_workspace used is master, even though there are lots of changes (fixing some issues) on the  cns2020 branch: https://github.com/Neurosim-lab/netpyne_workspace/compare/master...cns2020. Merge to master?

**Comment by lrebscher** [comment] 2021-02-23 13:50
Regarding 2.: I checked and it's [fixed](https://github.com/openworm/org.geppetto.frontend.jupyter/issues/111) on the development branch of the [jupyter-geppetto](https://github.com/openworm/org.geppetto.frontend.jupyter) notebook extension, but this wasn't yet released. So I can confirm, the issue is still present if you install netpyne without adding `--dev` flag to `install.py`.

**Comment by ddelpiano** [comment] 2021-02-24 17:26
closing in favour of #216 and #217

**Closed by ddelpiano** 2021-02-24 17:26 UTC
