### ISSUE TITLE
call resetModel after as confirmation dialog trigger implemented on 311

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/NetPyNE-UI#492] opened 2022-03-31 16:54 UTC
@ddelpiano as spin-off from #437 and after discussing this with @filippomc we consider that the best way to do this right now is to reset the model before loading a tutorial

**Comment by filippomc** [comment] 2022-04-01 08:01
Just to be clear: I wouldn't say this is the best way, but certainly it is the only implemented way _right now_. If there is some time, I'd also give a try to a key change in the main component, that should reset the state and break the update wormhole.

**Comment by ddelpiano** [comment] 2022-04-06 14:21
duplicate of #437 , please let's try to keep consistency in the cards rather than moving the issue from one card to another

**Closed by ddelpiano** 2022-04-06 14:21 UTC
