### ISSUE TITLE
Fix loading of Experiment/Trial results

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#320] opened 2021-06-14 08:04 UTC

**Comment by lrebscher** [comment] 2021-06-14 08:58
Loading only the net and simData JSON output file of a single batch combination throws TypeError. It works when I load everything with the `load` method.

```python
from netpyne import analysis
from netpyne import sim

file = "../workspace/experiments/MyExp-0/MyExp-0_0.json"
sim.initialize()
sim.loadNet(file)
sim.loadSimData(file)
analysis.iplotRaster(showFig=True)
```

```
Traceback (most recent call last):
  File "/Users/lrebscher/git/NetPyNE-UI/example/netpyne_test.py", line 8, in <module>
    sim.loadNet(file)
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/sim/load.py", line 307, in loadNet
    cell.createNEURONObj(prop)  # use same syntax as when creating based on high-level specs
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/cell/compartCell.py", line 417, in createNEURONObj
    self.addSynMechNEURONObj(synMech, synMechParams, sec, synMech['loc'])
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/cell/compartCell.py", line 464, in addSynMechNEURONObj
    synObj = getattr(h, synMechParams['mod'])
TypeError: 'NoneType' object is not subscriptable
```

When I use `sim.loadNet(file, instantiate=False)` it works as well.

**Comment by lrebscher** [comment] 2021-06-14 10:29
When I load the complete output with `sim.load(file)` netpyne throws a TypeErrow when trying to set the mapping parameters
```
Traceback (most recent call last):
  File "/Users/lrebscher/git/NetPyNE-UI/example/netpyne_test.py", line 6, in <module>
    sim.load(file)
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/sim/wrappers.py", line 374, in load
    sim.loadAll(filename, instantiate=instantiate, createNEURONObj=createNEURONObj)
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/sim/load.py", line 398, in loadAll
    loadNetParams(filename, data=data)
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/sim/load.py", line 208, in loadNetParams
    setup.setNetParams(data['net']['params'])
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/sim/setup.py", line 157, in setNetParams
    sim.net.params.setCfgMapping(sim.cfg) 
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/specs/netParams.py", line 607, in setCfgMapping
    self.setNestedParam(v, getattr(cfg, k))
  File "/Users/lrebscher/git/NetPyNE-UI/src/netpyne/netpyne/specs/netParams.py", line 601, in setNestedParam
    setattr(self, paramLabel, paramVal) # set simConfig params
TypeError: attribute name must be string, not 'Dict'
```

**Comment by lrebscher** [comment] 2021-06-14 10:30
JSON Output file: [MyExp-0_0.json.zip](https://github.com/MetaCell/NetPyNE-UI/files/6647645/MyExp-0_0.json.zip)

**Comment by lrebscher** [comment] 2021-06-23 09:49
@salvadord @joewgraham  can one of you guys take a look and let me know what the issue might be here?
E.g. faulty JSON or bug in netpyne?

I guess in the first case it requires the sim.cfg to be present. It's not so important anymore because we now load either the complete simulation or only the netParams + simConfig.

The second error is more important because it fails when loading a trial. I think the content of `mapping` should be correct.

**Comment by joewgraham** [comment] 2021-06-25 22:04
I did a lot of fixing in saving and loading this week, if you pull the latest dev branch now it should solve all your problems.  Let me know if it doesn't. @lrebscher

**Comment by lrebscher** [comment] 2021-06-28 09:35
@joewgraham could you merge these changes into the `mapping` branch? Need the functionality on this branch to test it. The issue I mentioned last exists only on this branch & I think it's specific to the batch param mapping.

**Comment by salvadord** [comment] 2021-06-28 16:27
@lrebscher I just merged dev into mapping -- let us know if the issue is solved. thanks

**Comment by lrebscher** [comment] 2021-06-30 09:22
I can confirm that it solved the `TypeError: attribute name must be string, not 'Dict'` error when loading a trial JSON.

But we also face a different error now:

![Bildschirmfoto 2021-06-30 um 11.17.04.png](https://images.zenhubusercontent.com/600fdb37a2c5e223bc039639/fd9a31d9-73ad-40a8-8256-d257c8b49870)

**Comment by lrebscher** [comment] 2021-06-30 09:49
@salvadord the issue in the case of the `attribute name must be string, not Dict` error is that the JSON output of a trial somehow contains a `__dict__` attribute in the `simCfg` object:

```
...
"mapping": {
    "__dict__": {},
    "popParams.E.numCells": [
        "popParams",
        "E",
        "numCells"
    ]
},
```

**Comment by salvadord** [comment] 2021-07-19 19:10
@lrebscher I'm not sure exactly where this __dict__ get's added, but for now the safest solution maybe is if you just add a condition to ignore the "__dict__" entry? I will also investigate and try to this from the netpyne backend side.

**Comment by lrebscher** [comment] 2021-07-21 08:17
I cannot really ignore it since this is created in netpyne and fails in netpyne. When I save the netParams to JSON I don't see the \_\_dict__ entry. But it's present in the `_data` output file that netpyne creates for a single simulation. And we use netpyne to load this output file.


Currently, I use a try-except clause in `netParams.py` to workaround this issue. This catches the exception [mentioned above](https://github.com/MetaCell/NetPyNE-UI/issues/320#issuecomment-860578144). @salvadord  you could push that to the mapping branch as temporary workaround

<img width="600" alt="Bildschirmfoto 2021-07-21 um 10 12 38" src="https://user-images.githubusercontent.com/7281685/126454964-6b266c94-ab5e-4d10-aaa4-0e1cc9fcf645.png">

**Comment by salvadord** [comment] 2021-07-27 23:13
@lrebscher I made changes in 'mapping' that hopefully fix the 2 issues above (and merged the latest dev changes):

Fixed setting cfgMapping nested params when not string: https://github.com/Neurosim-lab/netpyne/commit/afc364a6c0726186743f6e1415021dd239be97c4

Fixed defineCellShapes when sec[hObj] is not a h.Section(): https://github.com/Neurosim-lab/netpyne/commit/0fcec8ec0a6bbe06f4c413606f8104d65cfd7088

**Comment by lrebscher** [comment] 2021-07-28 08:49
Fix for cfgMapping works!

Fix for defineCellShapes, the `isinstance` check doesn't seem to work because `h.Section()` is not a type.

I changed it to `type(h.Section())` which yields `nrn.Section` class, that resolves the error.
But I don't see any neurons in the 3DViewer anymore when I load a JSON, don't know yet why that is the case 🤔 , I think that worked before we had this error, maybe related to some other changes in netpyne?

<img width="917" alt="Bildschirmfoto 2021-07-28 um 10 29 14" src="https://user-images.githubusercontent.com/7281685/127290567-cf3af548-1f73-45b8-a034-495acb839313.png">

**Comment by salvadord** [comment] 2021-07-28 14:09
@lrebscher thanks for the fix. 

It seems that the NEURON objects (eg h.Sections() are not being instantiated. This may be related to the some changes joe made for loading/saving recently. I will check.

**Comment by salvadord** [comment] 2021-07-28 14:52
@lrebscher  Ok yeah, there was a small bug in the new saving code such that the NEURON obj instantiation code was too indented and was never called. Fixed now in mapping and development branches
: https://github.com/Neurosim-lab/netpyne/commit/67baeab70b3820af76413383231611c011ceec40

**Comment by lrebscher** [comment] 2021-07-29 16:32
@salvadord  thx that worked! only the fix `type(h.Section())` in `compartCell.py:1398` is missing

**Comment by salvadord** [comment] 2021-07-29 16:44
@lrebscher great, made the change in mapping and dev branches

**Closed** 2021-08-11 15:18 UTC
Labels: bug
